# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HPxrtSFOZFxZZKaU1ZRb33F_fjKqI4Co
"""

import pandas as pd
import random as rd
import string as st
import sqlalchemy as sa

from sqlalchemy import create_engine, Column, Integer, String, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# --- 1. CLOUD CONNECTION ---
# Aiven provides 'postgres://', but SQLAlchemy requires 'postgresql://'
DB_URL = st.secrets["DB_URL"]
if DB_URL.startswith("postgres://"):
    DB_URL = DB_URL.replace("postgres://", "postgresql://", 1)

# Create the Engine
engine = create_engine(DB_URL)
Base = declarative_base()

# --- 2. THE DATABASE MODEL ---
class PasswordVault(Base):
    __tablename__ = 'user_passwords'

    # Serial ID: Autoincrements automatically in PostgreSQL
    id = Column(Integer, primary_key=True, autoincrement=True)
    website = Column(String(255), nullable=False)
    username = Column(String(255), nullable=False)
    password = Column(Text, nullable=False)

# Create the table on the Aiven server if it doesn't exist
Base.metadata.create_all(engine)

# Create a session
Session = sessionmaker(bind=engine)
session = Session()

def  generate_password(length):
    #the characters to choose from
    characters = st.ascii_letters + st.digits + st.punctuation
    while True:
        password = ''.join(rd.choice(characters) for i in range(length))
        # Ensure the password has at least one character from each category
        if (any(c in st.ascii_lowercase for c in password) and
            any(c in st.ascii_uppercase for c in password) and
            any(c in st.digits for c in password) and
            any(c in st.punctuation for c in password)):
            return password

#main function to run the program
def main():
    #hello message
    print("\n--- Welcome to The Strongest Password Manager 💪🛡️ ---")
    # the action the user wants to do
    Action = input(f" Type 'G'to generate/Save a password or 'R' to retrieve a password: ").upper()
    #generate password
    if Action == 'G':
        try:
            length = int(input(f"Enter password length (e.g., 16):"))

        except ValueError:
            print("Invalid entry. Password Should be Atleast 12 characters long.")
            length = 12

        new_password = generate_password(length)
        print(f"Generated Password: {new_password}")
        save_it = input(f"Would you like to save this password? (yes/no): ").lower()
    #save the password to the database
        if save_it == 'yes':
            site = input(f"Enter the website/app name: ").lower()
            user = input(f"Enter the username/email: ")

            new_entry = PasswordVault(website=site, username=user, password=new_password)
            session.add(new_entry)
            session.commit()
            print(f"✅ Your Password IsSuccessfully saved for {site}!")
        #retrieve password
    elif Action == 'R':
        target = input("Which website's password do you need? ").lower()
        # Retrieve Logic
        result = session.query(PasswordVault).filter_by(website=target).first()
        if result:
            print(f"\nCredentials Found:\nUser: {result.username}\nPass: {result.password}")
        else:
            print(f"\n❌ No password found for '{target}'.")
    else:
        print(f"Invalid action.")

if __name__ == "__main__":
    main()
