# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HPxrtSFOZFxZZKaU1ZRb33F_fjKqI4Co
"""
import pandas as pd
import sqlalchemy as sa
import streamlit as st
import random 
import string 

from sqlalchemy import create_engine, Column, Integer, String, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# --- 1. DATABASE SETUP ---
# We use st.secrets to keep your Aiven URL hidden from GitHub
try:
    DB_URL = st.secrets["DB_URL"]
    # Ensure the URL uses 'postgresql://' instead of 'postgres://'
    if DB_URL.startswith("postgres://"):
        DB_URL = DB_URL.replace("postgres://", "postgresql://", 1)
    
    engine = create_engine(DB_URL)
    Base = declarative_base()
except Exception as e:
    st.error("Could not find Database Secret. Please check Streamlit Settings.")
    st.stop()

# Define the Table Structure
class PasswordVault(Base):
    __tablename__ = 'user_passwords'
    id = Column(Integer, primary_key=True, autoincrement=True)
    website = Column(String(255), nullable=False)
    username = Column(String(255), nullable=False)
    password = Column(Text, nullable=False)

# Create table and session
Base.metadata.create_all(engine)
Session = sessionmaker(bind=engine)
session = Session()

# --- 2. PASSWORD GENERATION LOGIC ---
def generate_secure_password(length):
    characters = string.ascii_letters + string.digits + string.punctuation
    while True:
        pwd = ''.join(random.choice(characters) for _ in range(length))
        # Complexity Rules
        if (any(c.isupper() for c in pwd) and 
            any(c.isdigit() for c in pwd) and 
            any(c in string.punctuation for c in pwd)):
            return pwd

# --- 3. STREAMLIT UI ---
def main():
    st.set_page_config(page_title="Strongest Password Manager", page_icon="🛡️")
    st.title("🛡️ Strongest Password Manager")
    st.markdown("🔒 *Powered by Aiven PostgreSQL & SQLAlchemy*")

    # Sidebar for Settings
    st.sidebar.header("Configuration")
    pwd_length = st.sidebar.slider("Password Length", 8, 32, 16)

    # Main Tabs
    tab1, tab2 = st.tabs(["✨ Generate & Save", "🔍 Retrieve"])

    with tab1:
        st.subheader("Generate New Credentials")
        
        if st.button("Generate Password"):
            new_pw = generate_secure_password(pwd_length)
            st.session_state['generated_pw'] = new_pw
            st.success("New secure password generated!")
            st.code(new_pw, language="text")

        if 'generated_pw' in st.session_state:
            st.divider()
            st.write("### Save to Vault")
            site = st.text_input("Website or App Name (e.g., Facebook)").lower()
            user = st.text_input("Username or Email")
            
            if st.button("Confirm & Save to Cloud"):
                if site and user:
                    try:
                        new_entry = PasswordVault(
                            website=site, 
                            username=user, 
                            password=st.session_state['generated_pw']
                        )
                        session.add(new_entry)
                        session.commit()
                        st.balloons()
                        st.success(f"Successfully saved credentials for {site}!")
                        # Clear generated password after saving
                        del st.session_state['generated_pw']
                    except Exception as e:
                        session.rollback()
                        st.error(f"Database Error: {e}")
                else:
                    st.warning("Please fill in both fields.")

    with tab2:
        st.subheader("Search your Vault")
        search_target = st.text_input("Enter Website Name to Search").lower()
        
        if st.button("Retrieve Password"):
            if search_target:
                result = session.query(PasswordVault).filter_by(website=search_target).first()
                if result:
                    st.info(f"**Credentials for {search_target.capitalize()}:**")
                    st.write(f"**Username:** {result.username}")
                    st.write(f"**Password:**")
                    st.code(result.password, language="text")
                else:
                    st.error(f"No entry found for '{search_target}'.")
            else:
                st.warning("Please enter a website name.")

# --- 4. THE IMPORTANT RUN COMMAND ---
if __name__ == "__main__":
    main()
